project_id = "jsctrjeniokdekggvocj"

[functions.submit-grievance]
verify_jwt = false

[functions.classify-grievance]
verify_jwt = false

[functions.submit-bid]
verify_jwt = false

[functions.verify-task]
verify_jwt = false