// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsctrjeniokdekggvocj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzY3RyamVuaW9rZGVrZ2d2b2NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNzc5MDIsImV4cCI6MjA3MzY1MzkwMn0.ZCCklxqBk953LpIQxf8tiHJlhKWkPiURCCft3al9WkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});